Repository ansible-community/molecule-plugins, pull requests merged in 2023-05, with the labels that each got.

#149 Update driver.py documentation according to new plugin name
  src/molecule_plugins/podman/driver.py
Labels: documentation, enhancement

#123 Enhancement: Generate cookie cutter templates and apply linting on them
  .ansible-lint
  .ansible-lint-ignore
  .pre-commit-config.yaml
  requirements.yml
  tools/extract_plugin_names.py
  tools/generate-templates.sh
  tox.ini
Labels: enhancement

#151 deprecated(azure): replace VM type
  src/molecule_plugins/azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
Labels: deprecated

#159 lint tests
  test/azure/scenarios/driver/azure/molecule/multi-node/prepare.yml
  test/ec2/scenarios/driver/ec2/molecule/multi-node/converge.yml
  test/gce/scenarios/linux/converge.yml
  test/gce/scenarios/linux/create.yml
  test/gce/scenarios/linux/destroy.yml
  test/gce/scenarios/linux/handlers/main.yml
  test/gce/scenarios/linux/molecule.yml
  test/gce/scenarios/linux/prepare.yml
  test/gce/scenarios/linux/tasks/create_linux_instance.yml
  test/gce/scenarios/linux/tasks/create_windows_instance.yml
  test/gce/scenarios/linux/verify.yml
  test/gce/scenarios/windows/converge.yml
  test/gce/scenarios/windows/create.yml
  test/gce/scenarios/windows/destroy.yml
  test/gce/scenarios/windows/handlers/main.yml
  test/gce/scenarios/windows/molecule.yml
  test/gce/scenarios/windows/prepare.yml
  test/gce/scenarios/windows/tasks/create_linux_instance.yml
  test/gce/scenarios/windows/tasks/create_windows_instance.yml
  test/gce/scenarios/windows/verify.yml
  test/vagrant/scenarios/molecule/default-compat/create.yml
  test/vagrant/scenarios/molecule/default-compat/destroy.yml
  test/vagrant/scenarios/molecule/provider_config_options/verify.yml
  test/vagrant/scenarios/molecule/vagrant_root/verify.yml
Labels: bug

#154 feat: Add runtime entry on docker create playbook
  src/molecule_plugins/docker/playbooks/create.yml
Labels: docker, feature

#142 src/molecule_plugins/vagrant/modules/vagrant.py: Get rid of molecule dependency
  src/molecule_plugins/vagrant/modules/vagrant.py
Labels: bug, enhancement, vagrant
