Repository ansible-community/molecule-plugins, pull requests merged in 2023-03, with the labels that each got.

#111 Fix ci issue
  .ansible-lint
  molecule/test-podman/verify.yml
  src/molecule_plugins/docker/playbooks/validate-dockerfile.yml
  src/molecule_plugins/gce/playbooks/tasks/create_linux_instance.yml
  src/molecule_plugins/gce/playbooks/tasks/create_windows_instance.yml
  src/molecule_plugins/podman/driver.py
  src/molecule_plugins/podman/playbooks/create.yml
  src/molecule_plugins/podman/playbooks/validate-dockerfile.yml
  src/molecule_plugins/vagrant/modules/vagrant.py
  src/molecule_plugins/vagrant/playbooks/create.yml
  src/molecule_plugins/vagrant/playbooks/destroy.yml
  test/docker/test_func.py
  test/gce/scenarios/linux/create.yml
  test/gce/scenarios/linux/requirements.yml
  test/gce/scenarios/linux/tasks/create_linux_instance.yml
  test/gce/scenarios/linux/tasks/create_windows_instance.yml
  test/gce/scenarios/linux/verify.yml
  test/gce/scenarios/windows/create.yml
  test/gce/scenarios/windows/tasks/create_linux_instance.yml
  test/gce/scenarios/windows/tasks/create_windows_instance.yml
  test/gce/scenarios/windows/verify.yml
  test/vagrant/functional/test_func.py
  test/vagrant/scenarios/molecule/default-compat/create.yml
  test/vagrant/scenarios/molecule/default-compat/destroy.yml
  tox.ini
Labels: bug, skip-changelog

#112 Optimize CI
  .github/workflows/tox.yml
  test/gce/scenarios/linux/requirements.yml
  test/vagrant/scenarios/molecule/default-compat/destroy.yml
Labels: bug, skip-changelog

#91 README.md: Update plugin list
  README.md
Labels: bug, documentation

#101 Perform linting on Ansible playbooks
  .ansible-lint
  molecule/test-podman/converge.yml
  src/molecule_plugins/gce/playbooks/tasks/create_linux_instance.yml
  src/molecule_plugins/podman/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
Labels: skip-changelog

#110 install python3 only when ansible_system == Linux
  src/molecule_plugins/vagrant/playbooks/prepare.yml
Labels: bug, vagrant
