Repository ansible-community/molecule-plugins, pull requests merged in 2023-08, with the labels that each got.

#169 Fix ansible-lint errors
  .ansible-lint-ignore
  src/molecule_plugins/azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  src/molecule_plugins/azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  src/molecule_plugins/docker/playbooks/create.yml
  src/molecule_plugins/docker/playbooks/destroy.yml
  src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  src/molecule_plugins/gce/playbooks/create.yml
  src/molecule_plugins/gce/playbooks/destroy.yml
  src/molecule_plugins/gce/playbooks/handlers/main.yml
  src/molecule_plugins/gce/playbooks/tasks/create_linux_instance.yml
  src/molecule_plugins/gce/playbooks/tasks/create_windows_instance.yml
  src/molecule_plugins/podman/playbooks/create.yml
  tools/generate-templates.sh
Labels: enhancement

#173 podman: change ansible_async_dir only when $HOME is redefined
  src/molecule_plugins/podman/playbooks/create.yml
  src/molecule_plugins/podman/playbooks/destroy.yml
  tox.ini
Labels: enhancement, podman

#177 Update tests to use v6-alpha1 molecule version
  .ansible-lint-ignore
  pyproject.toml
  test/azure/functional/test_azure.py
  test/ec2/functional/test_ec2.py
  test/gce/functional/test_func.py
  tools/generate-templates.sh
Labels: bug

#178 Revert "Update tests to use v6-alpha1 molecule version"
  .ansible-lint-ignore
  pyproject.toml
  test/azure/functional/test_azure.py
  test/ec2/functional/test_ec2.py
  test/gce/functional/test_func.py
  tools/generate-templates.sh
Labels: bug

#170 Prevent empty destroy from deleting other EC2 instances
  .ansible-lint-ignore
  src/molecule_plugins/ec2/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
Labels: bug
