Repository ansible-community/molecule-plugins, pull requests merged in 2023-04, with the labels that each got.

#95 feature(Docker): Add support for `platform` parameter
  src/molecule_plugins/docker/playbooks/create.yml
Labels: feature

#117 enhancement: Add pacman support to vagrant plugin
  src/molecule_plugins/vagrant/playbooks/prepare.yml
Labels: enhancement, vagrant

#120 Docker playbooks are also running when tags are set
  src/molecule_plugins/docker/playbooks/create.yml
  src/molecule_plugins/docker/playbooks/destroy.yml
  src/molecule_plugins/docker/playbooks/validate-dockerfile.yml
Labels: feature

#105 enhancement: update azure cookie cutter template to support a more recent ansible syntax
  src/molecule_plugins/azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  src/molecule_plugins/azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  src/molecule_plugins/azure/cookiecutter/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
Labels: bug

#85 Install rsync as dependency
  src/molecule_plugins/docker/playbooks/Dockerfile.j2
Labels: bug

#129 Require py39 or newer
  pyproject.toml
Labels: bug

#133 Adding python-vagrant as dep to vagrant plugin
  pyproject.toml
Labels: bug

#141 Add safe filter for raw args (vagrant)
  src/molecule_plugins/vagrant/modules/vagrant.py
Labels: bug, vagrant

#145 ruff: address EXE
  pyproject.toml
  src/molecule_plugins/gce/playbooks/files/windows_auth.py
  src/molecule_plugins/vagrant/modules/vagrant.py
  test/gce/scenarios/linux/files/windows_auth.py
  test/gce/scenarios/windows/files/windows_auth.py
Labels: skip-changelog
